SWE_final/gals-custom-user/hello_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls import include, url
from django.urls import reverse

#admin/ is where the admin adds users
#accounts/ is where the user logs in ect.

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/home/', TemplateView.as_view(template_name='home.html'), name='hockey'),
    path('accounts/accounts/home/student_dash.html', TemplateView.as_view(template_name='student_dash.html'), name='studenthome'),
   
]

SWE_final/gals-custom-user/users/urls.py
# accounts/urls.py
from django.urls import path

from . import views
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls import include, url


urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('initial/', TemplateView.as_view(template_name = "initial.html"), name = 'initial'),
    path('survey/index/', views.IndexView.as_view(), name="index"),
    path('survey/responsive/', views.ResponsiveView.as_view(), name="respond"),
    path('survey/new/', views.BuildView.as_view(), name="survey_create"),
    path('survey/new/creation-success/', views.SuccessView.as_view(), name="survey_creation_success"),
    path('survey/<int:survey_id>/', views.SurveyDetailView.as_view(), name="survey_detail"),
    path('surveystudent/<int:survey_id>/', views.SurveyDetailViewStudent.as_view(), name="survey_detail_student"),
    path('survey/<int:survey_id>/edit/', views.SurveyEditView.as_view(), name="survey_edit"),
    path('survey/<int:survey_id>/response/', views.RespondView.as_view(), name="survey_respond"),
    path('survey/<int:survey_id>/response/<int:response_id>/', views.RespondView.as_view(), name="response"),
    path('home/create_class/', views.Class, name='create_class'),
    path('accounts/home/', views.homekyle, name='home'),
    #path('home/reg_class/', views.regClass, name='reg_class')
   # path('accounts/home/reg_class/', views.regClass, name='reg_class'),
    path('survey/export/xls/$', views.export_users_xls, name='export_users_xls'),
    path('filtered/', views.selectedCourse, name='selectedCourse'),
    path('filteredStudent/', views.selectedCourseStudent, name='selectedCourseStudent'),
    
]

SWE_final/gals-custom-user/users/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext_lazy as _
from django.utils.timezone import now

from .managers import CustomUserManager
from dynamic_forms.models import FormField, ResponseField
from django import forms



class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(unique = True, max_length = 50)
    last_name = models.CharField(unique = True, max_length = 50)
    eagle_id = models.CharField(max_length = 9, primary_key=True)
    is_instructor = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email

#WIP, comment this out if you're doing something else
class Course(models.Model):
    course_name = models.CharField(max_length = 30)
    course_id = models.CharField(unique = True, max_length = 12, primary_key = True)
    course_date = models.CharField(max_length = 10)
    course_section = models.CharField(max_length = 3)
    course_semester = models.CharField(max_length = 10)
    
   
# #
class CourseInstructor(models.Model):
    course = models.ManyToManyField(Course)
    eagle_id = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
# #

# #

class CourseTeam(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    name = models.CharField(unique = True, max_length = 50)

class CourseStudent(models.Model):
    course = models.ManyToManyField(Course)
    eagle_id = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    team = models.ManyToManyField(CourseTeam)


class Survey(models.Model):
    startdate = models.DateTimeField(default = now)
    enddate = models.DateTimeField(default = now)
    topic = models.CharField(max_length=100)
    course_survey = models.ManyToManyField(Course)
    #start_date = models.DateField(default='')
    #submission_date = models.DateField(default='')
    form = FormField()
    def __str__(self):
        return "Survey #{}: ".format(self.pk, self.topic)


class SurveyResponse(models.Model):
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE)
    response = ResponseField()

SWE_final/gals-custom-user/templates/build.html
{% extends 'base.html' %}

{% block content %}


<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" value="submit">Submit</button>
</form>
{% endblock %}

SWE_final/gals-custom-user/templates/create_class.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static%}
{% block title %}Create Class{% endblock %}

{% block main %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Creative - Bootstrap 3 Responsive Admin Template">
    <meta name="author" content="GeeksLabs">
    <meta name="keyword" content="Creative, Dashboard, Admin, Template, Theme, Bootstrap, Responsive, Retina, Minimal">
    <link rel="shortcut icon" href="img/favicon.png">
  
    <title>Creative - Bootstrap Admin Template</title>
  
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- bootstrap theme -->
    <link href= "{% static 'css/bootstrap-theme.css' %}" rel="stylesheet">
    <!--external css-->
    <!-- font icon -->
    <link href=" {% static 'css/elegant-icons-style.css' %}" rel="stylesheet" />
    <link href=" {% static 'css/font-awesome.min.css' %}" rel="stylesheet" />
    <!-- full calendar css-->
    <link href=" {% static 'assets/fullcalendar/fullcalendar/bootstrap-fullcalendar.css' %}" rel="stylesheet" />
    <link href=" {% static 'assets/fullcalendar/fullcalendar/fullcalendar.css' %}" rel="stylesheet" />
    <!-- easy pie chart-->
    <link href=" {% static 'assets/jquery-easy-pie-chart/jquery.easy-pie-chart.css' %}" rel="stylesheet" type="text/css" media="screen" />
    <!-- owl carousel -->
    <link rel="stylesheet" href=" {% static 'css/owl.carousel.css' %}" type="text/css">
    <link href=" {% static 'css/jquery-jvectormap-1.2.2.css' %}" rel="stylesheet">
    <!-- Custom styles -->
    <link rel="stylesheet" href=" {% static 'css/fullcalendar.css' %}">
    <link href=" {% static 'css/widgets.css' %}" rel="stylesheet">
    <link href=" {% static 'css/style.css' %}" rel="stylesheet">
    <link href=" {% static 'css/style-responsive.css' %}" rel="stylesheet" />
    <link href=" {% static 'css/xcharts.min.css' %}" rel=" stylesheet">
    <link href=" {% static 'css/jquery-ui-1.10.4.min.css' %}" rel="stylesheet">
  </head>

<div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="panel panel-default">
            <!-- <div class="panel-heading">
                <h3 class="panel-title">Create A New Survey</h3>
            </div> -->

            <form method="POST">
                {% csrf_token %}
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <!-- <div class="form-group">
                                <label for="question">Enter Survey Question</label>
                                {% render_field form.question class="form-control" rows="3" %}
                            </div> -->
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="option1" id="1">course name</label>
                                {% render_field form.course_name class="form-control" id="fuck" %}
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="course_id" id="2">course_id</label>
                                {% render_field form.course_id class="form-control" id="12"%}
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="course_date">course_date</label>
                                {% render_field form.course_date class="form-control"%}
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="course_section">course_section</label>
                                {% render_field form.course_section class="form-control" %}
                            </div>
                        </div>

                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="course_semester" >course_semester</label>
                                {% render_field form.course_semester class="form-control"%}
                            </div>
                        </div>


                    </div>
                    <div class="row">
                        <hr />
                        <div class="col-lg-4">
                            <a href="{% url 'home' %}">
                            <button style = "font-size: x-small;"type="submit" class="btn btn-info">Submit</button>
                        </div>
                    </a>
                    </div>
                </div>
            </form>

        </div>
    </div>
</div>
{% endblock %}

SWE_final/gals-custom-user/templates/filtered.html
{% extends 'base.html' %}
{%load static%}

{% block content %}
<!DOCTYPE html>
<html lang="en">
    <!DOCTYPE html>
    <html lang="en">
    
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta name="description" content="Creative - Bootstrap 3 Responsive Admin Template">
      <meta name="author" content="GeeksLabs">
      <meta name="keyword" content="Creative, Dashboard, Admin, Template, Theme, Bootstrap, Responsive, Retina, Minimal">
      <link rel="shortcut icon" href="img/favicon.png">
    
      <title>Creative - Bootstrap Admin Template</title>
    
      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
      <!-- bootstrap theme -->
      <link href= "{% static 'css/bootstrap-theme.css' %}" rel="stylesheet">
      <!--external css-->
      <!-- font icon -->
      <link href=" {% static 'css/elegant-icons-style.css' %}" rel="stylesheet" />
      <link href=" {% static 'css/font-awesome.min.css' %}" rel="stylesheet" />
      <!-- full calendar css-->
      <link href=" {% static 'assets/fullcalendar/fullcalendar/bootstrap-fullcalendar.css' %}" rel="stylesheet" />
      <link href=" {% static 'assets/fullcalendar/fullcalendar/fullcalendar.css' %}" rel="stylesheet" />
      <!-- easy pie chart-->
      <link href=" {% static 'assets/jquery-easy-pie-chart/jquery.easy-pie-chart.css' %}" rel="stylesheet" type="text/css" media="screen" />
      <!-- owl carousel -->
      <link rel="stylesheet" href=" {% static 'css/owl.carousel.css' %}" type="text/css">
      <link href=" {% static 'css/jquery-jvectormap-1.2.2.css' %}" rel="stylesheet">
      <!-- Custom styles -->
      <link rel="stylesheet" href=" {% static 'css/fullcalendar.css' %}">
      <link href=" {% static 'css/widgets.css' %}" rel="stylesheet">
      <link href=" {% static 'css/style.css' %}" rel="stylesheet">
      <link href=" {% static 'css/style-responsive.css' %}" rel="stylesheet" />
      <link href=" {% static 'css/xcharts.min.css' %}" rel=" stylesheet">
      <link href=" {% static 'css/jquery-ui-1.10.4.min.css' %}" rel="stylesheet">
    </head>
<script src='https://kit.fontawesome.com/a076d05399.js'></script>

  <!-- HEADER START: -->
  <header class="header dark-bg">
    <div class="toggle-nav">
      <div class="icon-reorder tooltips" data-placement="bottom"><i class="icon_menu"></i></div>
    </div>

    <!--logo start-->
    <a href=" {% url 'home' %}" class="logo">Instructor <span class="lite">View</span></a>
    <!--logo end-->

  </header>
  <body>
    <section id="main-content">
        <section class="wrapper">
          <!--overview start-->
          <div class="row" >
            <div class="col-lg-12">
              <h3 class="page-header"><i class="fas fa-poll"></i> Peer Assesments</h3>

            </div>
          </div>

          <div class="row">
            <a href="{% url 'survey_create' %}">
                  <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                    <div class="info-box blue-bg">
                        <i class="fas fa-plus"></i>
                      <div class="title">Create New Survey</div>
                    </div>
                  </div>
                  </a>
                
                      <ul>
                        {% for survey in data %}
                        <li><a href="{% url 'survey_detail' survey.pk %}">
                            <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                                <div class="info-box brown-bg">
                                    <i class="fas fa-poll"></i>
                            <div class="title">
                            {{survey.topic}}
                        </div>
                        </a></li>
                        {% endfor %}
                        </ul>
                   
                    </div>
                  </div>
                </a>

        
          <!--/.row-->

          </div><br><br>

          <div class="row">
            <div class="col-md-6 portlets">

          <!-- project team & activity end -->

        </section>
      </section>
      <!--main content end-->
    </section>
  
      </body>


{% endblock %}

SWE_final/gals-custom-user/templates/filteredStudent.html
{% extends 'base.html' %}
{%load static%}

{% block content %}
<!DOCTYPE html>
<html lang="en">
    <!DOCTYPE html>
    <html lang="en">
    
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta name="description" content="Creative - Bootstrap 3 Responsive Admin Template">
      <meta name="author" content="GeeksLabs">
      <meta name="keyword" content="Creative, Dashboard, Admin, Template, Theme, Bootstrap, Responsive, Retina, Minimal">
      <link rel="shortcut icon" href="img/favicon.png">
    
      <title>Creative - Bootstrap Admin Template</title>
    
      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
      <!-- bootstrap theme -->
      <link href= "{% static 'css/bootstrap-theme.css' %}" rel="stylesheet">
      <!--external css-->
      <!-- font icon -->
      <link href=" {% static 'css/elegant-icons-style.css' %}" rel="stylesheet" />
      <link href=" {% static 'css/font-awesome.min.css' %}" rel="stylesheet" />
      <!-- full calendar css-->
      <link href=" {% static 'assets/fullcalendar/fullcalendar/bootstrap-fullcalendar.css' %}" rel="stylesheet" />
      <link href=" {% static 'assets/fullcalendar/fullcalendar/fullcalendar.css' %}" rel="stylesheet" />
      <!-- easy pie chart-->
      <link href=" {% static 'assets/jquery-easy-pie-chart/jquery.easy-pie-chart.css' %}" rel="stylesheet" type="text/css" media="screen" />
      <!-- owl carousel -->
      <link rel="stylesheet" href=" {% static 'css/owl.carousel.css' %}" type="text/css">
      <link href=" {% static 'css/jquery-jvectormap-1.2.2.css' %}" rel="stylesheet">
      <!-- Custom styles -->
      <link rel="stylesheet" href=" {% static 'css/fullcalendar.css' %}">
      <link href=" {% static 'css/widgets.css' %}" rel="stylesheet">
      <link href=" {% static 'css/style.css' %}" rel="stylesheet">
      <link href=" {% static 'css/style-responsive.css' %}" rel="stylesheet" />
      <link href=" {% static 'css/xcharts.min.css' %}" rel=" stylesheet">
      <link href=" {% static 'css/jquery-ui-1.10.4.min.css' %}" rel="stylesheet">
    </head>
<script src='https://kit.fontawesome.com/a076d05399.js'></script>

 
<!-- HEADER START: -->
<header class="header student-bg">
    <div class="toggle-nav">
      <div class="icon-reorder tooltips" data-placement="bottom"><i class="icon_menu"></i></div>
    </div>

    <!--logo start-->
    <a href= " {% url 'home' %}" class="logo">Student <span class="lite">View</span></a>
  </header>
  <body>
    <section id="main-content">
        <section class="wrapper">
          <!--overview start-->
          <div class="row" >
            <div class="col-lg-12">
              <h3 class="page-header"><i class="fas fa-poll"></i> Peer Assesments</h3>

            </div>
          </div>

          <div class="row">
       
                
                      <ul>
                        {% for survey in data %}
                        <li><a href="{% url 'survey_respond' survey.pk %}">
                            <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                                <div class="info-box brown-bg">
                                    <i class="fas fa-poll"></i>
                            <div class="title">
                            {{survey.topic}}
                        </div>
                        </a></li>
                        {% endfor %}
                        </ul>
                   
                    </div>
                  </div>
                </a>

        
          <!--/.row-->

          </div><br><br>

          <div class="row">
            <div class="col-md-6 portlets">

          <!-- project team & activity end -->

        </section>
      </section>
      <!--main content end-->
    </section>
  
      </body>


{% endblock %}

SWE_final/gals-custom-user/templates/homekyle.html
{% extends 'base.html' %}

{% block title %}Homepage{% endblock %}

{% block main %}
<div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Available Suveys</h3>
            </div>

            <ul class="list-group">
                {% for poll in polls %}
                <li class="list-group-item">
                    <strong>{{ poll.question }}</strong>
                    <span class="pull-right">
                        <a href="{% url 'vote' poll.id %}" class="btn btn-info btn-xs">Vote</a> &nbsp;
                        <a href="{% url 'results' poll.id %}" class="btn btn-default btn-xs">View Results</a> &nbsp;
                    </span>
                </li>
                {% endfor %}
            </ul>

        </div>
    </div>
</div>
{% endblock %}

SWE_final/gals-custom-user/templates/reg_class.html
{% extends 'kylebase.html' %}
{% load static%}
{% block title %}reg class{% endblock %}

{% block main %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Creative - Bootstrap 3 Responsive Admin Template">
    <meta name="author" content="GeeksLabs">
    <meta name="keyword" content="Creative, Dashboard, Admin, Template, Theme, Bootstrap, Responsive, Retina, Minimal">
    <link rel="shortcut icon" href="img/favicon.png">

    <title>Creative - Bootstrap Admin Template</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- bootstrap theme -->
    <link href= "{% static 'css/bootstrap-theme.css' %}" rel="stylesheet">
    <!--external css-->
    <!-- font icon -->
    <link href=" {% static 'css/elegant-icons-style.css' %}" rel="stylesheet" />
    <link href=" {% static 'css/font-awesome.min.css' %}" rel="stylesheet" />
    <!-- full calendar css-->
    <link href=" {% static 'assets/fullcalendar/fullcalendar/bootstrap-fullcalendar.css' %}" rel="stylesheet" />
    <link href=" {% static 'assets/fullcalendar/fullcalendar/fullcalendar.css' %}" rel="stylesheet" />
    <!-- easy pie chart-->
    <link href=" {% static 'assets/jquery-easy-pie-chart/jquery.easy-pie-chart.css' %}" rel="stylesheet" type="text/css" media="screen" />
    <!-- owl carousel -->
    <link rel="stylesheet" href=" {% static 'css/owl.carousel.css' %}" type="text/css">
    <link href=" {% static 'css/jquery-jvectormap-1.2.2.css' %}" rel="stylesheet">
    <!-- Custom styles -->
    <link rel="stylesheet" href=" {% static 'css/fullcalendar.css' %}">
    <link href=" {% static 'css/widgets.css' %}" rel="stylesheet">
    <link href=" {% static 'css/style.css' %}" rel="stylesheet">
    <link href=" {% static 'css/style-responsive.css' %}" rel="stylesheet" />
    <link href=" {% static 'css/xcharts.min.css' %}" rel=" stylesheet">
    <link href=" {% static 'css/jquery-ui-1.10.4.min.css' %}" rel="stylesheet">
  </head>
<div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Register for Classes</h3>
            </div>




            <form method="POST">
              {% csrf_token %}


              <h3> PLEASE CONFIRM STUDENT ID  </h3>

            <input type="text" name="student" value="student" >
            <h3> SELECT COURSE  </h3>
            <ul class="list-group">
                {% for course in course %}
                <li class="list-group-item">
                    <input type="radio" name="course" value={{ course.course_id }}>
                    <strong>{{ course.course_name }}</strong>
                </li>
                {% endfor %}
            </ul>



                            <button style="font-size:10px"type="submit" class="btn btn-info" href="student_dash.html">
                                Submit
                            </button>
                        </form>
                    </div>
                </div>
            </div>


{% endblock %}

SWE_final/gals-custom-user/templates/respond.html
{% extends 'base.html' %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    {{form}}
    <button type="submit" value="submit">Submit</button>
</form>
{% endblock %}

SWE_final/gals-custom-user/templates/survey_detail.html
{% extends 'base.html' %}
{% load static%}
{% block content %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Creative - Bootstrap 3 Responsive Admin Template">
    <meta name="author" content="GeeksLabs">
    <meta name="keyword" content="Creative, Dashboard, Admin, Template, Theme, Bootstrap, Responsive, Retina, Minimal">
    <link rel="shortcut icon" href="img/favicon.png">
  
    <title>Creative - Bootstrap Admin Template</title>
  
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- bootstrap theme -->
    <link href= "{% static 'css/bootstrap-theme.css' %}" rel="stylesheet">
    <!--external css-->
    <!-- font icon -->
    <link href=" {% static 'css/elegant-icons-style.css' %}" rel="stylesheet" />
    <link href=" {% static 'css/font-awesome.min.css' %}" rel="stylesheet" />
    <!-- full calendar css-->
    <link href=" {% static 'assets/fullcalendar/fullcalendar/bootstrap-fullcalendar.css' %}" rel="stylesheet" />
    <link href=" {% static 'assets/fullcalendar/fullcalendar/fullcalendar.css' %}" rel="stylesheet" />
    <!-- easy pie chart-->
    <link href=" {% static 'assets/jquery-easy-pie-chart/jquery.easy-pie-chart.css' %}" rel="stylesheet" type="text/css" media="screen" />
    <!-- owl carousel -->
    <link rel="stylesheet" href=" {% static 'css/owl.carousel.css' %}" type="text/css">
    <link href=" {% static 'css/jquery-jvectormap-1.2.2.css' %}" rel="stylesheet">
    <!-- Custom styles -->
    <link rel="stylesheet" href=" {% static 'css/fullcalendar.css' %}">
    <link href=" {% static 'css/widgets.css' %}" rel="stylesheet">
    <link href=" {% static 'css/style.css' %}" rel="stylesheet">
    <link href=" {% static 'css/style-responsive.css' %}" rel="stylesheet" />
    <link href=" {% static 'css/xcharts.min.css' %}" rel=" stylesheet">
    <link href=" {% static 'css/jquery-ui-1.10.4.min.css' %}" rel="stylesheet">
  </head>
<a href="{% url 'index' %}">All Surveys</a>
<br>
<a href="edit/">Edit Survey</a>
<br>


<p>Responses</p>
<hr>
{% for surveyresponse in object.surveyresponse_set.all %}
<ul>
    {% for k, v in surveyresponse.response.items %}
    <li><strong>{{k}}: </strong> {{v}}</li>
    {% endfor %}
</ul>
<hr>
{% endfor %}
<a href="{% url 'export_users_xls' %}">Download Responses</a>
{% endblock %}

SWE_final/gals-custom-user/templates/survey_detail_student.html
{% extends 'base.html' %}
{% load static%}
{% block content %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Creative - Bootstrap 3 Responsive Admin Template">
    <meta name="author" content="GeeksLabs">
    <meta name="keyword" content="Creative, Dashboard, Admin, Template, Theme, Bootstrap, Responsive, Retina, Minimal">
    <link rel="shortcut icon" href="img/favicon.png">
  
    <title>Creative - Bootstrap Admin Template</title>
  
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- bootstrap theme -->
    <link href= "{% static 'css/bootstrap-theme.css' %}" rel="stylesheet">
    <!--external css-->
    <!-- font icon -->
    <link href=" {% static 'css/elegant-icons-style.css' %}" rel="stylesheet" />
    <link href=" {% static 'css/font-awesome.min.css' %}" rel="stylesheet" />
    <!-- full calendar css-->
    <link href=" {% static 'assets/fullcalendar/fullcalendar/bootstrap-fullcalendar.css' %}" rel="stylesheet" />
    <link href=" {% static 'assets/fullcalendar/fullcalendar/fullcalendar.css' %}" rel="stylesheet" />
    <!-- easy pie chart-->
    <link href=" {% static 'assets/jquery-easy-pie-chart/jquery.easy-pie-chart.css' %}" rel="stylesheet" type="text/css" media="screen" />
    <!-- owl carousel -->
    <link rel="stylesheet" href=" {% static 'css/owl.carousel.css' %}" type="text/css">
    <link href=" {% static 'css/jquery-jvectormap-1.2.2.css' %}" rel="stylesheet">
    <!-- Custom styles -->
    <link rel="stylesheet" href=" {% static 'css/fullcalendar.css' %}">
    <link href=" {% static 'css/widgets.css' %}" rel="stylesheet">
    <link href=" {% static 'css/style.css' %}" rel="stylesheet">
    <link href=" {% static 'css/style-responsive.css' %}" rel="stylesheet" />
    <link href=" {% static 'css/xcharts.min.css' %}" rel=" stylesheet">
    <link href=" {% static 'css/jquery-ui-1.10.4.min.css' %}" rel="stylesheet">
  </head>
  <a href="{% url 'home' %}">Go back</a>
<p>Responses</p>
<hr>
{% for surveyresponse in object.surveyresponse_set.all %}
<ul>
    {% for k, v in surveyresponse.response.items %}
    <li><strong>{{k}}: </strong> {{v}}</li>
    {% endfor %}
</ul>
<hr>
{% endfor %}
<a href="{% url 'export_users_xls' %}">Download Responses</a>
{% endblock %}

SWE_final/gals-custom-user/templates/survey_edit.html
{% extends 'base.html' %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" value="submit">Submit</button>
</form>
{% endblock %}